location_parent: /mnt/thredds/wootten_2020
acknowledgement: &acknowledgement 
  - 
link: *acknowledgement
title: &title 
  - "Developing and Analyzing Statistically Downscaled Climate Projections for the South Central U.S"
link_title: *title
project: "Characterizing Uncertainties in Climate Projections to Support Regional Decision-Making"
id: cida.usgs.gov/TTU_2019
creator_name: Adrienne Wootten
creator_email: amwootte@ou.edu
creator_org: University of Oklahoma
creator_url: https://www.ou.edu
publication_date: '2020-07-01'
creation_date: '2019-09-25'
summary: >- 
  Global climate models (GCMs) are numerically complex, computationally intensive, 
  physics-based research tools used to simulate our planet’s inter-connected climate system. 
  In addition to improving the scientific understanding of how the large-scale climate system 
  works, GCM simulations of past and future climate conditions can be useful in applied research
  contexts. When seeking to apply information from global-scale climate projections to address 
  local- and regional-scale climate questions, GCM-generated datasets often undergo statistical 
  post-processing generally known as statistical downscaling (hereafter, SD). There are many 
  different SD techniques, with all using information from observations to address GCM biases 
  and to provide information at finer spatial scales than that of a GCM, thereby yielding data 
  products often considered more suitable for use in climate impacts-related applications. 
    This collection of statistically downscaled future climate projections includes 81 sets of 
  SD-processed projections of daily high temperature, daily low temperature, and daily total 
  precipitation across the south-central United States. The 81 sets can be viewed as a 3x3x3x3 
  matrix, created based on a combination of three GCMs from the CMIP5 archive (CCSM4, MIROC5, 
  and MPI-ESM-LR), each of which simulated 21st century climate responses for three different 
  future atmospheric composition scenarios (known as representative concentration pathways or 
  RCPs 2.6, 4.5, and 8.5). Three different SD techniques were employed, and each used three 
  gridded observation-based data products to train (i.e. calibrate) the SD methods. The three 
  downscaling techniques include a delta method (DeltaSD), an equi-distant quantile mapping 
  method (EDQM), and a piecewise asynchronous regression method (PARM). The observational data 
  products used for training were Daymet v. 2.1, Livneh v. 1.2, and PRISM AN81d v. D1. The 
  resulting SD-processed projections are on a 10 km by 10 km grid covering the south-central 
  United States (all of AR, KS, LA, NM, OK, TX, and portions of CO and MO). Both historical 
  baseline files (1981-2005) and future projections (2006-2099) are provided, as appropriate.
    Though not exhaustive, these downscaled climate projections for the south central US region 
  represent a range of potential future climate trajectories that can serve as a component of 
  climate impacts research studies. That 81 sets of future projections, and not just one, are 
  provided is indicative that some uncertainties exist regarding the trajectory of the 21st 
  century climate change, though all show notable warming. Uncertainties in how human activity 
  may change future atmospheric composition are represented by the different RCP scenarios. 
  Differences in how sensitive the surface climate of this region will be to atmospheric 
  composition changes are sampled by the use of different GCMs. Similarly, because each SD 
  method has different performance characteristics and observational products differ, the use of different SD techniques and training data set combinations acknowledges that SD methodological choices influence the value-added statistically refined climate projection data products. Applied researchers may explore aspects of their applications’ sensitivities to some climate projection uncertainties by sampling from these 81 sets of SD data products. However, this collection should not be considered comprehensive in spanning the entire scope of SD processed climate projections for the south central US region. These climate projection data products are provided as is without any warranty and no agreement to support subsequent
  projects based on this dataset, beyond providing the data to public domain through the USGS 
  GeoData Portal.

lat_min: 26.05
lat_max: 39.95
lon_min: -108.95
lon_max: -90.05
resolution: daily
keywords:

references: 
  - "Dixon K.W., A.M. Wootten, M.J. Nath, J. Lanzante,  D.J. Adams-Smith, C.E. Whitlock, C.F. Gaitán, R.A. McPherson, 2020: South Central Climate Projections Evaluation Project (C-PrEP), South Central Climate Adaptation Science Center, Norman, Oklahoma, USA."
  - "Wootten A.M., K. W. Dixon, D.J. Adams-Smith, Renee A. McPherson, in press: Statistically Downscaled Precipitation Sensitivity to Gridded Observation Data and Downscaling Technique, International Journal of Climatology."
start_time: &start
  - "1950-07-01"
time_start: *start
end_time: &end
  - "2099-12-31"
time_end: *end
sciencebase_id: '5ee7b8a882ce3bd58d82ef9f'
attribute_description:
    - ddx_url: https://cida.usgs.gov/thredds/dodsC/wootten_2020.ddx
    - ddx_description: "OPeNDAP description"
opendap_url: https://cida.usgs.gov/thredds/dodsC/wootten_2020
note: false
