location: 
acknowledgement: https://nelson.wisc.edu/ccr/resources/dynamical-downscaling/index.php
title: Dynamical Downscaling for the Midwest and Great Lakes Basin
project: University of Wisconsin-Madison Dynamical Downscaling
id: 
creator_name: Michael Notaro
creator_email: mnotaro@wisc.edu
summary: >- 
  Six global climate models (GCMs) from the Coupled Model Intercomparison Project Phase Five (CMIP5) were
  dynamically downscaled to 25-km grid spacing according to the representative concentration pathway 8.5 (RCP8.5) 
  scenario using the International Centre for Theoretical Physics (ICTP) Regional Climate Model Version Four (RegCM4). 
  These GCMs include the Centre National de Recherches Meteorologiques Coupled Global Climate Model Version Five (CNRM-CM5), 
  the Model for Interdisciplinary Research on Climate Version Five (MIROC5), the Institut Pierre Simon Laplace Coupled Model 
  Version Five-Medium Resolution (IPSL-CM5-MR), the Meteorological Research Institute Coupled Global Climate Model Version 
  Three (MRI-CGCM3), the Centre for Australian Weather and Climate Research, Australia GCM (ACCESS1-0), and the National 
  Oceanic and Atmospheric Administration Geophysical Fluid Dynamics Laboratory model (GFDL-ESM2M).
lat_min: 31.077085
lat_max: 54.030327
lon_min: -100.042442
lon_max: -60.740917
