nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d01_monthly_CESM,Time,west_east,south_north HDD_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d01_monthly_CESM,Time,west_east,south_north CDD_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d01_monthly_CESM,Time,west_east,south_north T2MAX_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d01_monthly_CESM,Time,west_east,south_north T2MIN_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d01_monthly_CESM,Time,west_east,south_north T2MEAN_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d01_monthly_CESM,Time,west_east,south_north T2P02_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d01_monthly_CESM,Time,west_east,south_north T2P05_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d01_monthly_CESM,Time,west_east,south_north T2P10_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d01_monthly_CESM,Time,west_east,south_north T2P25_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d01_monthly_CESM,Time,west_east,south_north T2P50_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d01_monthly_CESM,Time,west_east,south_north T2P75_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d01_monthly_CESM,Time,west_east,south_north T2P90_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d01_monthly_CESM,Time,west_east,south_north T2P95_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d01_monthly_CESM,Time,west_east,south_north T2P98_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d01_monthly_CESM,Time,west_east,south_north T2MAXDAVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d01_monthly_CESM,Time,west_east,south_north T2MINDAVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d01_monthly_CESM,Time,west_east,south_north PRECIP_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d01_monthly_CESM,Time,west_east,south_north KECOLAVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d01_monthly_CESM,Time,west_east,south_north PWATAVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d01_monthly_CESM,Time,west_east,south_north SLPAVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d01_monthly_CESM,Time,west_east,south_north Z500AVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d01_monthly_CESM,Time,west_east,south_north Q700AVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d01_monthly_CESM,Time,west_east,south_north T700AVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d01_monthly_CESM,Time,west_east,south_north WS850AVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d01_monthly_CESM,Time,west_east,south_north WS250AVG_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d01_monthly_CESM,Time,west_east,south_north MDRN_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d01_monthly_CESM,Time,west_east,south_north DP01_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d01_monthly_CESM,Time,west_east,south_north DP05_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d01_monthly_CESM,Time,west_east,south_north DP10_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d01_monthly_CESM,Time,west_east,south_north DT00_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d01_monthly_CESM,Time,west_east,south_north DT32_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d01_monthly_CESM,Time,west_east,south_north DT90_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d01_monthly_CESM,Time,west_east,south_north DX32_d01_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d01_monthly_CNRM,Time,west_east,south_north HDD_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d01_monthly_CNRM,Time,west_east,south_north CDD_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d01_monthly_CNRM,Time,west_east,south_north T2MAX_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d01_monthly_CNRM,Time,west_east,south_north T2MIN_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d01_monthly_CNRM,Time,west_east,south_north T2MEAN_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d01_monthly_CNRM,Time,west_east,south_north T2P02_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d01_monthly_CNRM,Time,west_east,south_north T2P05_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d01_monthly_CNRM,Time,west_east,south_north T2P10_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d01_monthly_CNRM,Time,west_east,south_north T2P25_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d01_monthly_CNRM,Time,west_east,south_north T2P50_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d01_monthly_CNRM,Time,west_east,south_north T2P75_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d01_monthly_CNRM,Time,west_east,south_north T2P90_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d01_monthly_CNRM,Time,west_east,south_north T2P95_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d01_monthly_CNRM,Time,west_east,south_north T2P98_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d01_monthly_CNRM,Time,west_east,south_north T2MAXDAVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d01_monthly_CNRM,Time,west_east,south_north T2MINDAVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d01_monthly_CNRM,Time,west_east,south_north PRECIP_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d01_monthly_CNRM,Time,west_east,south_north KECOLAVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d01_monthly_CNRM,Time,west_east,south_north PWATAVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d01_monthly_CNRM,Time,west_east,south_north SLPAVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d01_monthly_CNRM,Time,west_east,south_north Z500AVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d01_monthly_CNRM,Time,west_east,south_north Q700AVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d01_monthly_CNRM,Time,west_east,south_north T700AVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d01_monthly_CNRM,Time,west_east,south_north WS850AVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d01_monthly_CNRM,Time,west_east,south_north WS250AVG_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d01_monthly_CNRM,Time,west_east,south_north MDRN_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d01_monthly_CNRM,Time,west_east,south_north DP01_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d01_monthly_CNRM,Time,west_east,south_north DP05_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d01_monthly_CNRM,Time,west_east,south_north DP10_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d01_monthly_CNRM,Time,west_east,south_north DT00_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d01_monthly_CNRM,Time,west_east,south_north DT32_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d01_monthly_CNRM,Time,west_east,south_north DT90_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d01_monthly_CNRM,Time,west_east,south_north DX32_d01_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d02_monthly_CESM,Time,west_east,south_north HDD_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d02_monthly_CESM,Time,west_east,south_north CDD_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d02_monthly_CESM,Time,west_east,south_north T2MAX_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d02_monthly_CESM,Time,west_east,south_north T2MIN_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d02_monthly_CESM,Time,west_east,south_north T2MEAN_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d02_monthly_CESM,Time,west_east,south_north T2P02_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d02_monthly_CESM,Time,west_east,south_north T2P05_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d02_monthly_CESM,Time,west_east,south_north T2P10_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d02_monthly_CESM,Time,west_east,south_north T2P25_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d02_monthly_CESM,Time,west_east,south_north T2P50_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d02_monthly_CESM,Time,west_east,south_north T2P75_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d02_monthly_CESM,Time,west_east,south_north T2P90_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d02_monthly_CESM,Time,west_east,south_north T2P95_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d02_monthly_CESM,Time,west_east,south_north T2P98_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d02_monthly_CESM,Time,west_east,south_north T2MAXDAVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d02_monthly_CESM,Time,west_east,south_north T2MINDAVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d02_monthly_CESM,Time,west_east,south_north PRECIP_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d02_monthly_CESM,Time,west_east,south_north KECOLAVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d02_monthly_CESM,Time,west_east,south_north PWATAVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d02_monthly_CESM,Time,west_east,south_north SLPAVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d02_monthly_CESM,Time,west_east,south_north Z500AVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d02_monthly_CESM,Time,west_east,south_north Q700AVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d02_monthly_CESM,Time,west_east,south_north T700AVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d02_monthly_CESM,Time,west_east,south_north WS850AVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d02_monthly_CESM,Time,west_east,south_north WS250AVG_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d02_monthly_CESM,Time,west_east,south_north MDRN_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d02_monthly_CESM,Time,west_east,south_north DP01_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d02_monthly_CESM,Time,west_east,south_north DP05_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d02_monthly_CESM,Time,west_east,south_north DP10_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d02_monthly_CESM,Time,west_east,south_north DT00_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d02_monthly_CESM,Time,west_east,south_north DT32_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d02_monthly_CESM,Time,west_east,south_north DT90_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d02_monthly_CESM,Time,west_east,south_north DX32_d02_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d02_monthly_CNRM,Time,west_east,south_north HDD_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d02_monthly_CNRM,Time,west_east,south_north CDD_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d02_monthly_CNRM,Time,west_east,south_north T2MAX_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d02_monthly_CNRM,Time,west_east,south_north T2MIN_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d02_monthly_CNRM,Time,west_east,south_north T2MEAN_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d02_monthly_CNRM,Time,west_east,south_north T2P02_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d02_monthly_CNRM,Time,west_east,south_north T2P05_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d02_monthly_CNRM,Time,west_east,south_north T2P10_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d02_monthly_CNRM,Time,west_east,south_north T2P25_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d02_monthly_CNRM,Time,west_east,south_north T2P50_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d02_monthly_CNRM,Time,west_east,south_north T2P75_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d02_monthly_CNRM,Time,west_east,south_north T2P90_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d02_monthly_CNRM,Time,west_east,south_north T2P95_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d02_monthly_CNRM,Time,west_east,south_north T2P98_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d02_monthly_CNRM,Time,west_east,south_north T2MAXDAVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d02_monthly_CNRM,Time,west_east,south_north T2MINDAVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d02_monthly_CNRM,Time,west_east,south_north PRECIP_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d02_monthly_CNRM,Time,west_east,south_north KECOLAVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d02_monthly_CNRM,Time,west_east,south_north PWATAVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d02_monthly_CNRM,Time,west_east,south_north SLPAVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d02_monthly_CNRM,Time,west_east,south_north Z500AVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d02_monthly_CNRM,Time,west_east,south_north Q700AVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d02_monthly_CNRM,Time,west_east,south_north T700AVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d02_monthly_CNRM,Time,west_east,south_north WS850AVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d02_monthly_CNRM,Time,west_east,south_north WS250AVG_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d02_monthly_CNRM,Time,west_east,south_north MDRN_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d02_monthly_CNRM,Time,west_east,south_north DP01_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d02_monthly_CNRM,Time,west_east,south_north DP05_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d02_monthly_CNRM,Time,west_east,south_north DP10_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d02_monthly_CNRM,Time,west_east,south_north DT00_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d02_monthly_CNRM,Time,west_east,south_north DT32_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d02_monthly_CNRM,Time,west_east,south_north DT90_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d02_monthly_CNRM,Time,west_east,south_north DX32_d02_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d03_monthly_CESM,Time,west_east,south_north HDD_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d03_monthly_CESM,Time,west_east,south_north CDD_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d03_monthly_CESM,Time,west_east,south_north T2MAX_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d03_monthly_CESM,Time,west_east,south_north T2MIN_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d03_monthly_CESM,Time,west_east,south_north T2MEAN_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d03_monthly_CESM,Time,west_east,south_north T2P02_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d03_monthly_CESM,Time,west_east,south_north T2P05_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d03_monthly_CESM,Time,west_east,south_north T2P10_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d03_monthly_CESM,Time,west_east,south_north T2P25_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d03_monthly_CESM,Time,west_east,south_north T2P50_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d03_monthly_CESM,Time,west_east,south_north T2P75_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d03_monthly_CESM,Time,west_east,south_north T2P90_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d03_monthly_CESM,Time,west_east,south_north T2P95_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d03_monthly_CESM,Time,west_east,south_north T2P98_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d03_monthly_CESM,Time,west_east,south_north T2MAXDAVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d03_monthly_CESM,Time,west_east,south_north T2MINDAVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d03_monthly_CESM,Time,west_east,south_north PRECIP_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d03_monthly_CESM,Time,west_east,south_north KECOLAVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d03_monthly_CESM,Time,west_east,south_north PWATAVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d03_monthly_CESM,Time,west_east,south_north SLPAVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d03_monthly_CESM,Time,west_east,south_north Z500AVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d03_monthly_CESM,Time,west_east,south_north Q700AVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d03_monthly_CESM,Time,west_east,south_north T700AVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d03_monthly_CESM,Time,west_east,south_north WS850AVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d03_monthly_CESM,Time,west_east,south_north WS250AVG_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d03_monthly_CESM,Time,west_east,south_north MDRN_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d03_monthly_CESM,Time,west_east,south_north DP01_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d03_monthly_CESM,Time,west_east,south_north DP05_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d03_monthly_CESM,Time,west_east,south_north DP10_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d03_monthly_CESM,Time,west_east,south_north DT00_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d03_monthly_CESM,Time,west_east,south_north DT32_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d03_monthly_CESM,Time,west_east,south_north DT90_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d03_monthly_CESM,Time,west_east,south_north DX32_d03_monthly_CESM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?HDD_d03_monthly_CNRM,Time,west_east,south_north HDD_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?CDD_d03_monthly_CNRM,Time,west_east,south_north CDD_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAX_d03_monthly_CNRM,Time,west_east,south_north T2MAX_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MIN_d03_monthly_CNRM,Time,west_east,south_north T2MIN_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MEAN_d03_monthly_CNRM,Time,west_east,south_north T2MEAN_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P02_d03_monthly_CNRM,Time,west_east,south_north T2P02_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P05_d03_monthly_CNRM,Time,west_east,south_north T2P05_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P10_d03_monthly_CNRM,Time,west_east,south_north T2P10_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P25_d03_monthly_CNRM,Time,west_east,south_north T2P25_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P50_d03_monthly_CNRM,Time,west_east,south_north T2P50_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P75_d03_monthly_CNRM,Time,west_east,south_north T2P75_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P90_d03_monthly_CNRM,Time,west_east,south_north T2P90_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P95_d03_monthly_CNRM,Time,west_east,south_north T2P95_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2P98_d03_monthly_CNRM,Time,west_east,south_north T2P98_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MAXDAVG_d03_monthly_CNRM,Time,west_east,south_north T2MAXDAVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T2MINDAVG_d03_monthly_CNRM,Time,west_east,south_north T2MINDAVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PRECIP_d03_monthly_CNRM,Time,west_east,south_north PRECIP_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?KECOLAVG_d03_monthly_CNRM,Time,west_east,south_north KECOLAVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?PWATAVG_d03_monthly_CNRM,Time,west_east,south_north PWATAVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?SLPAVG_d03_monthly_CNRM,Time,west_east,south_north SLPAVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Z500AVG_d03_monthly_CNRM,Time,west_east,south_north Z500AVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?Q700AVG_d03_monthly_CNRM,Time,west_east,south_north Q700AVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?T700AVG_d03_monthly_CNRM,Time,west_east,south_north T700AVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS850AVG_d03_monthly_CNRM,Time,west_east,south_north WS850AVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?WS250AVG_d03_monthly_CNRM,Time,west_east,south_north WS250AVG_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?MDRN_d03_monthly_CNRM,Time,west_east,south_north MDRN_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP01_d03_monthly_CNRM,Time,west_east,south_north DP01_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP05_d03_monthly_CNRM,Time,west_east,south_north DP05_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DP10_d03_monthly_CNRM,Time,west_east,south_north DP10_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT00_d03_monthly_CNRM,Time,west_east,south_north DT00_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT32_d03_monthly_CNRM,Time,west_east,south_north DT32_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DT90_d03_monthly_CNRM,Time,west_east,south_north DT90_d03_monthly_CNRM.nc 
nccopy -k nc7 -d 1 -c time/1,lat/40,lon/40 -u http://localhost:8080/thredds/dodsC/thredds/puertoRico/monthly.ncml?DX32_d03_monthly_CNRM,Time,west_east,south_north DX32_d03_monthly_CNRM.nc 
