library("ncdf4")
library("chron")

originDate<-strptime("2000-01-01","%Y-%m-%d")
endDate<-strptime("2018-01-01","%Y-%m-%d")
times<-seq(from=originDate,to=endDate,by='years')
times<-round(julian(times,origin=originDate))
time_vec<-1:length(times)
nc_time_dim <- ncdim_def('time','',time_vec,create_dimvar=FALSE)
nc_time_var <- ncvar_def('time','days since 2000-01-01', nc_time_dim, -999, prec='integer')
nc_file<-nc_create('times_annual.nc',list(nc_time_var))
var<-ncvar_put(nc_file,nc_time_var,times)
nc_close(nc_file)

endDate<-strptime("2019-10-31","%Y-%m-%d")
times<-seq(from=originDate,to=endDate,by='months')
times<-round(julian(times,origin=originDate))
time_vec<-1:length(times)
nc_time_dim <- ncdim_def('time','',time_vec,create_dimvar=FALSE)
nc_time_var <- ncvar_def('time','days since 2000-01-01', nc_time_dim, -999, prec='integer')
nc_file<-nc_create('times_monthly.nc',list(nc_time_var))
var<-ncvar_put(nc_file,nc_time_var,times)
nc_close(nc_file)
